### ISSUE TITLE
feat: Core rego engine rework and QoL improvements

### ISSUE THREAD

**Issue by liamg** [aquasecurity/defsec#951]
- [x] Rule metadata (`__rego_metadata__`) should be parsed from the [official rego annotation format](https://www.openpolicyagent.org/docs/latest/annotations/).
- [x] We should also use annotations to replace `__rego_input__` to simplify and standardise the rule code.
- [x] Allow full customisation via new metadata - as in https://github.com/aquasecurity/defsec/issues/955
- [x] The rego input schema should be documented with json schema and applied in annotations for all scanners (e.g. dockerfile, terraform, aws etc.)
  - [x] Dockerfile
  - [x] Kubernetes
  - [x] RBAC
  - [x] Cloud State (blocked by https://github.com/open-policy-agent/opa/issues/5166)
- [x] Helper methods should be made available to ensure the rule authoring process is as simple as possible, like the Go rule experience.
- [x] The defsec-specific `data.lib` code should be replaced with Go functions that are made available to the rego at runtime.
- [ ] Update rego metadata docs
- [ ] Add schema to docs, and generate documentation from all json schema documents
- [x] ~PR to OPA to add remote schema support - see https://github.com/open-policy-agent/opa/issues/4478~
- [x] ~Link remote schema in check metadata~
- [x] Fix https://github.com/aquasecurity/tfsec/issues/1901
- [x] Fix https://github.com/open-policy-agent/opa/issues/5166

This is a prerequisite for https://github.com/aquasecurity/trivy/issues/2917
